
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: library
  password: Incorrect12

development:
  adapter: postgresql
  database: hello_rails_back_end_development
  username: library
  password: Incorrect12
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: hello_rails_back_end_test
  username: library
  password: Incorrect12
  encoding: unicode
  host: localhost
  pool: 5

production:
  <<: *default
  database: hello_rails_back_end_production
  username: hello_rails_back_end
  password: <%= ENV["HELLO_RAILS_BACK_END_DATABASE_PASSWORD"] %>

