Message.create(content: "I love coding and programming 1")
Message.create(content: "I love coding and programming 2")
Message.create(content: "I love coding and programming 3")
Message.create(content: "I love coding and programming 4")
Message.create(content: "I love coding and programming 5")